### ISSUE TITLE
Charging station showing up twice

### ISSUE THREAD

**Issue by langiole** [citrineos/citrineos-operator-ui#29]
Despite only having one charging station in the database, two separate tables containing the same station are being displayed in the charging station view:

<img width="1464" alt="Screenshot 2024-10-24 at 13 57 31" src="https://github.com/user-attachments/assets/318ee28a-7f31-4530-8b17-614c3ef4dba7">

**Comment by elliot-sabitov** [comment]
@langiole please pull the latest `rc-0.2.0` branch and you should not see the two table. You are seeing 2 tables because I put the new generic table below the old table implementation so that we can easily compare and make sure that we did not miss any functionality. In the newer versions, the old table implementations was removed. Please note, that in Transactions, you may see 2 tables, for the same reason, because I added the new generic implementation below the old implementation to try and compare the two and make sure that we keep the same functionality

**Comment by langiole** [comment]
@elliot-sabitov Pulling `rc-0.2.0` and running `npm run build` results in:
<img width="1324" alt="Screenshot 2024-10-25 at 01 30 38" src="https://github.com/user-attachments/assets/9983e30c-205a-48bc-a5dc-601aa7837c40">

I do not see `ChargingStationSequenceType` within the base module of the core repo.

**Comment by elliot-sabitov** [comment]
Please try pulling latest CORE `rc-1.5.0` branch and be sure to rebuild CORE so that Vite in Operator UI can pick up the changes from `Base`. You may need to do `npm run fi` again for the changes to be picked up, but I think I saw that when I rebuilt CORE, it rebuilds `Base` and Vite in Operator UI picks the changes up right away

**Comment by langiole** [comment]
Thank you @elliot-sabitov.

Looks good now when running `rc-0.2.0`.

I needed to update package json to specify core version `rc-1.5.0` since it currently specifies `rc-1.4.3`.

**Comment by elliot-sabitov** [comment]
I don't think 1.5.0 is in NPM yet, so you may need to clone CORE locally and place `citrineos-core` side by side in same directory as `citrineos-operator-ui` repo folder. We have Vite in Operator UI set up to check if CORE is present locally and use the local CORE code if it is found.
